# Generated by Django 5.0 on 2024-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookedhotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_booked',
            name='check_in_time',
            field=models.DateTimeField(),
        ),
    ]
