# Generated by Django 5.0 on 2024-04-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookedhotel', '0002_alter_hotel_booked_check_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_booked',
            name='booked_status',
            field=models.CharField(choices=[('Booked', 'booked'), ('Pre Booked', 'pre booked')], max_length=20),
        ),
    ]
